Repository team-pream/pream-web, pull requests merged in 2024-11, with the labels that each got.

#90 [PREAM-146] Carousel 너비 수정
  src/App.tsx
  src/components/carousel/index.tsx
  src/libs/kako-map/index.ts
  src/pages/mypage/pages/address/components/addAddress/index.tsx
  src/pages/mypage/pages/address/components/button/index.tsx
  src/pages/mypage/pages/address/index.tsx
Labels: 🚨🐛 Bug

#112 [PREAM-148] 원하는 상품을 검색할 수 있다
  public/icons/emotional_pet_icon.svg
  src/api/products/index.ts
  src/assets/icons/EmotionalPetIcon.tsx
  src/assets/icons/index.ts
  src/components/search-bar/index.tsx
  src/pages/categories/index.tsx
  src/pages/main/index.tsx
  src/pages/products/index.tsx
  src/pages/products/pages/index.ts
  src/pages/products/pages/search/components/message/index.styles.ts
  src/pages/products/pages/search/components/message/index.tsx
  src/pages/products/pages/search/index.styles.ts
  src/pages/products/pages/search/index.tsx
  src/queries/products/index.ts
  src/queries/query-keys.ts
  src/types/products/index.ts
Labels: ✨ Feature

#122 [PREAM-163] 결제 실패 페이지 화면 구현
  public/icons/failure_icon.svg
  src/assets/icons/FailureIcon.tsx
  src/assets/icons/index.ts
  src/pages/orders/pages/complete/index.tsx
  src/pages/orders/pages/failure/index.styles.ts
  src/pages/orders/pages/failure/index.tsx
Labels: ✨ Feature

#133 [PREAM-167] 상품 목록페이지, 검색 페이지 수정
  src/pages/products/components/index.ts
  src/pages/products/components/message/index.styles.ts
  src/pages/products/components/message/index.tsx
  src/pages/products/pages/list/index.tsx
  src/pages/products/pages/search/index.tsx
Labels: 🚨🐛 Bug

#137 [PREAM-168] 빌드 에러 해결
  .gitignore
  .svgrrc.cjs
  src/assets/icons/AppBarBack.tsx
  src/assets/icons/AppbarBack.tsx
  src/assets/icons/Complete.tsx
  src/assets/icons/DropdownFold.tsx
  src/assets/icons/DropdownUnfold.tsx
  src/assets/icons/EmotionalPetIcon.tsx
  src/assets/icons/FabPlus.tsx
  src/assets/icons/GnbCategory.tsx
  src/assets/icons/GnbHome.tsx
  src/assets/icons/GnbMy.tsx
  src/assets/icons/KakaoLogo.tsx
  src/assets/icons/LikeOff.tsx
  src/assets/icons/LikeOn.tsx
  src/assets/icons/Logo.tsx
  src/assets/icons/MypageUploadImage.tsx
  src/assets/icons/ProductsDetailOption.tsx
  src/assets/icons/Search.tsx
  src/assets/icons/SelectCat.tsx
  src/assets/icons/SelectDog.tsx
  src/assets/icons/UploadPlus.tsx
  src/components/action-sheet/index.stories.ts
  src/components/chip/radio-group/index.stories.tsx
  src/pages/mypage/pages/address/components/addAddress/index.tsx
  src/pages/orders/pages/order/components/shipping-info/index.tsx
  src/pages/orders/pages/order/hooks/use-search-address.ts
  src/pages/products/pages/upload/index.tsx
Labels: 🚨🐛 Bug

#138 [PREAM-166] 제품상세의 시간, 상태 반영
  src/pages/products/pages/detail/components/product-info/index.tsx
  src/pages/products/pages/detail/index.tsx
  src/pages/products/pages/detail/types/index.ts
  src/pages/products/pages/detail/utils/index.ts
Labels: ✨ Feature

#139 [PREAM-164] 필터링 상태일 때 수정
  src/pages/products/components/index.ts
  src/pages/products/components/message/index.styles.ts
  src/pages/products/components/message/index.tsx
  src/pages/products/pages/list/index.tsx
  src/pages/products/pages/search/index.tsx
Labels: 🚨🐛 Bug

#141 [PREAM-168] 추가적인 빌드 에러 해결
  src/assets/icons/FailureIcon.tsx
  src/pages/onboarding/index.tsx
Labels: 🚨🐛 Bug

#147 [PREAM-172] 상품 목록 썸네일 이미지 사이즈 통일
  src/pages/products/pages/list/index.styles.ts
Labels: 🎨 Design

#151 [PREAM-164] 카테고리 이름 수정
  src/pages/products/pages/list/index.tsx
Labels: 🚨🐛 Bug

#160 [PREAM-164] 검색 페이지 예약 중 표시 UI 추가
  src/pages/products/pages/search/index.tsx
Labels: 🚨🐛 Bug

#158 [PREAM-145] 반려동물 타입 선택 시 글자 색 변경
  src/pages/onboarding/components/pet-type/index.styles.ts
Labels: 🚨🐛 Bug

#162 [PREAM-170] 404 페이지 구현
  public/icons/not_found.svg
  src/App.tsx
  src/assets/icons/NotFound.tsx
  src/assets/icons/index.ts
  src/pages/index.ts
  src/pages/not-found/index.styles.ts
  src/pages/not-found/index.tsx
  src/pages/products/index.tsx
Labels: ✨ Feature

#175 [PREAM-164] 검색페이지 상품 썸네일 이미지 사이즈 수정
  src/pages/products/pages/search/index.styles.ts
Labels: 🚨🐛 Bug

#178 [PREAM-153] Loader 적용
  package.json
  pnpm-lock.yaml
  src/pages/categories/components/category-item/index.styles.ts
  src/pages/categories/components/category-item/indexSkeleton.tsx
  src/pages/categories/index.styles.ts
  src/pages/categories/index.tsx
  src/pages/mypage/pages/sales-list/index.style.ts
  src/pages/mypage/pages/sales-list/index.tsx
  src/pages/orders/pages/complete/index.styles.ts
  src/pages/orders/pages/complete/index.tsx
  src/pages/products/pages/detail/index.style.ts
  src/pages/products/pages/detail/index.tsx
  src/pages/products/pages/list/index.styles.ts
  src/pages/products/pages/list/index.tsx
  src/pages/products/pages/list/indexSkeleton.tsx
Labels: 🚨🐛 Bug
