Repository team-pream/pream-web, pull requests merged in 2024-10, with the labels that each got.

#33 [PREAM-31] Input 컴포넌트 구현
  src/components/input/index.stories.tsx
  src/components/input/index.styles.ts
  src/components/input/index.tsx
  src/styles/theme.ts
Labels: ✨ Feature

#35 [PREAM-94] Storybook 배포를 위한 workflow 작성
  .github/workflows/deploy-storybook.yml
  .gitignore
  README.md
  package.json
  pnpm-lock.yaml
Labels: ✨ Feature

#31 [PREAM-76] Radio group 컴포넌트 구현
  src/components/app-bar/index.stories.tsx
  src/components/app-bar/index.tsx
  src/components/button/index.stories.ts
  src/components/button/index.styles.ts
  src/components/button/index.tsx
  src/components/fab/index.stories.tsx
  src/components/fab/index.tsx
  src/components/gnb/index.stories.ts
  src/components/index.ts
  src/components/radio-group/index.stories.tsx
  src/components/radio-group/index.styles.ts
  src/components/radio-group/index.tsx
  src/components/search-bar/index.stories.ts
  src/components/search-bar/index.tsx
  src/components/text/index.stories.ts
  src/components/text/index.tsx
Labels: ✨ Feature

#38 [PREAM-108] 공통 UI 컴포넌트 적용
  .github/workflows/deploy-storybook.yml
  src/App.tsx
  src/api/api.ts
  src/api/category/index.ts
  src/api/index.ts
  src/components/app-bar/index.styles.ts
  src/components/app-bar/index.tsx
  src/components/button/index.styles.ts
  src/components/fab/index.styles.ts
  src/components/gnb/index.styles.ts
  src/components/gnb/index.tsx
  src/components/index.ts
  src/pages/auth/index.tsx
  src/pages/auth/pages/kakao-callback/index.tsx
  src/pages/category/components/category-item/index.styles.ts
  src/pages/category/components/category-item/index.tsx
  src/pages/category/index.styles.ts
  src/pages/category/index.tsx
  src/pages/index.ts
  src/pages/login/index.styles.ts
  src/pages/login/index.tsx
  src/queries/category/index.ts
  tsconfig.app.json
Labels: ✨ Feature, ⚙️ Refactor

#42 [PREAM-34] 카테고리에 해당하는 상품 조회
  src/api/products/index.ts
  src/pages/category/components/category-item/index.tsx
  src/pages/products/index.styles.ts
  src/pages/products/index.tsx
  src/queries/products/index.ts
  src/queries/query-keys.ts
  src/styles/theme.ts
  src/types/index.ts
Labels: ✨ Feature

#44 [PREAM-97] 페이지별 경로 상수화
  src/constants/routes.ts
  src/pages/auth/pages/kakao-callback/index.tsx
Labels: ✨ Feature

#48 [PREAM-118] Dialog 컴포넌트 추가
  src/components/button/index.stories.ts
  src/components/button/index.styles.ts
  src/components/button/index.tsx
  src/components/dialog/index.stories.ts
  src/components/dialog/index.styles.ts
  src/components/dialog/index.tsx
  src/components/index.ts
  src/components/input/index.stories.tsx
  src/components/input/index.styles.ts
  src/components/input/index.tsx
  src/styles/colors.ts
  src/styles/theme.ts
Labels: ✨ Feature, 🎨 Design

#52 [PREAM-120] GNB 컴포넌트에서 좋아요 탭 제거
  src/components/gnb/index.tsx
Labels: 🎨 Design

#58 [PREAM-123] Layout 컴포넌트 추가
  src/components/action-sheet/index.styles.ts
  src/components/fab/index.styles.ts
  src/components/fab/index.tsx
  src/components/index.ts
  src/components/layout/index.styles.ts
  src/components/layout/index.tsx
  src/pages/category/components/category-item/index.styles.ts
  src/pages/category/index.styles.ts
  src/pages/category/index.tsx
  src/pages/login/index.tsx
  src/pages/products/index.styles.ts
  src/pages/products/index.tsx
  src/styles/global-style.tsx
  src/styles/theme.ts
Labels: ✨ Feature

#65 [PREAM-57] 판매 등록 페이지 레이아웃
  package.json
  pnpm-lock.yaml
  public/icons/upload_plus.svg
  src/App.tsx
  src/assets/icons/AppbarBack.tsx
  src/assets/icons/KakaoLogo.tsx
  src/assets/icons/UploadPlus.tsx
  src/assets/icons/index.ts
  src/components/app-bar/index.stories.tsx
  src/components/input/index.styles.ts
  src/components/layout/index.styles.ts
  src/components/layout/index.tsx
  src/pages/products/index.tsx
  src/pages/products/pages/index.ts
  src/pages/products/pages/product-list/index.styles.ts
  src/pages/products/pages/product-list/index.tsx
  src/pages/products/pages/upload/components/info/index.styles.ts
  src/pages/products/pages/upload/components/info/index.tsx
  src/pages/products/pages/upload/index.styles.ts
  src/pages/products/pages/upload/index.tsx
  src/styles/global-style.tsx
  src/styles/normalize.css
Labels: 🎨 Design
